### ISSUE TITLE
Minor request: zero pad time split measurement sets

### ISSUE THREAD

**Issue by ajstewart** [lofar-astron/PiLL#11]
Hopefully a simple request - it would be nice to zero pad (at least one) the 'TCX.split', such that if a split value is chosen that results in more than 10 sets, they will be easier to manage.

```L229405_SAP000_SB000_uv.postsagecal.HBAflag.dppp_1248548D2t_65MHz_TC0.split``` --> ```L229405_SAP000_SB000_uv.postsagecal.HBAflag.dppp_1248548D2t_65MHz_TC00.split```

**Comment by adrabent** [comment]
You can check whether the new script is dealing with the numbering properly.

**Comment by ajstewart** [comment]
It's nearly there, but I think you need ```.zfill(zeros+1)``` because the zfill argument is the 'width'. So for example with 2 digit chunks ```zeros     = int(math.log10(99))``` == 1 but then the chunk==4 so str(4).zfill(1) will result in '4'.

Edit: Well, actually better to add 1 to the initial zeros= line at the beginning of the script.
