### ISSUE TITLE
executable_args/parmdb_collector.py error on CEP3

### ISSUE THREAD

**Issue by mknapp55** [lofar-astron/PiLL#12]
I'm running the pipeline on CEP3  The pipeline failed with the following message:

`2017-03-24 13:49:08 INFO    genericpipeline.vdsmaker: Wrote combined VDS file: /data/scratch/gj411/workdir/pipeline/vds/pipeline.gvds
2017-03-24 13:49:08 DEBUG   genericpipeline.vdsmaker: Unlinking temporary files
2017-03-24 13:49:08 INFO    genericpipeline.vdsmaker: vdsmaker done
2017-03-24 13:49:08 INFO    genericpipeline.vdsmaker: recipe vdsmaker completed
2017-03-24 13:49:08 INFO    genericpipeline: Beginning step findvds
2017-03-24 13:49:08 INFO    genericpipeline: Beginning step globaldb
2017-03-24 13:49:09 INFO    genericpipeline: Running task: executable_args
2017-03-24 13:49:09 ERROR   genericpipeline: *******************************************
2017-03-24 13:49:09 ERROR   genericpipeline: Failed pipeline run: pipeline
2017-03-24 13:49:09 ERROR   genericpipeline: Detailed exception information:
2017-03-24 13:49:09 ERROR   genericpipeline: <type 'exceptions.TypeError'>
2017-03-24 13:49:09 ERROR   genericpipeline: /opt/cep/LofIm/daily/Thu/lofar_build/install/gnu_opt/bin/parmdb_collector.py is an invalid value for ExecField executable
2017-03-24 13:49:09 ERROR   genericpipeline: *******************************************
2017-03-24 13:49:09 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
2017-03-24 13:49:10 WARNING genericpipeline: recipe genericpipeline completed with errors`

This python file (parmdb_collector.py) does not exist at the location specified by the pipeline on CEP3.  Where can I find it?  I didn't see it in the scripts/ folder of this repo.  

I've attached only top section of the parset (where I made changes) for reference.
[LBA_pipeline_gj411.parset.txt](https://github.com/lofar-astron/PiLL/files/868385/LBA_pipeline_gj411.parset.txt)

**Comment by ajstewart** [comment]
Have you initiated losoto on cep3 before running with:

```source /home/fdg/scripts/losoto/tools/lofarinit.[c]sh```

parmdb_collector.py is part of losoto.

**Comment by tammojan** [comment]
> Have you initiated losoto on cep3 before running with:
> 
> source /home/fdg/scripts/losoto/tools/lofarinit.[c]sh
> 
> parmdb_collector.py is part of losoto.

The correct command for sourcing losoto on cep3 is `use Losoto`

**Comment by ajstewart** [comment]
@tammojan Ah thanks for the correction, my bad! I copied it from the cookbook v20 in chapter 6 - it must need correcting.

**Comment by mknapp55** [comment]
Yes, I have Losoto in my list of packages that are added on startup (.mypackages) in my home directory.  I ran 'use Losoto' explicitly too just to check and got the same result.

**Comment by AHorneffer** [comment]
> /opt/cep/LofIm/daily/Thu/lofar_build/install/gnu_opt/bin/parmdb_collector.py

Hmmm....
```
/home/horneffer
(horneffer)lhd002> use Losoto

/home/horneffer
(horneffer)lhd002> which parmdb_collector.py
/opt/cep/losoto/current/bin/parmdb_collector.py
```

I guess the real problem is that on CEP3 the LoSoTo executables are not in the same directory as the general LOFAR executables.

**Comment by ajstewart** [comment]
Ah, I see it's similar to what I have to do.

You'll see in the parset that the losoto tools are called with their locations as:

```globaldbFR.control.executable                                =   {{ lofar_directory }}/bin/parmdb_collector.py```

The lofar_directory is set to LOFARROOT.

However this is not true for losoto bin scripts on CEP3:
```
stewart@lhd002:~$ echo $LOFARROOT
/opt/cep/LofIm/daily/Fri/lofar_build/install/gnu_opt

stewart@lhd002:~$ which parmdb_collector.py
/opt/cep/losoto/current/bin/parmdb_collector.py
```

So what I do in this case is create a new variable in the parset for the losoto path and then replace this throughout. So in this case losoto_directory=/opt/cep/losoto/current and then change the losoto tools.

There should probably be a separate losoto directory field in the parset as it can vary from system to system.

**Comment by mknapp55** [comment]
@ajstewart Good suggestion.  I added !losoto_directory to the top of my parset and then changed the relevant steps to point there.  Working so far...

**Comment by adrabent** [comment]
@ajstewart 
This is correct. PiLL is only tested on "machines outside of CEP3" which have installed the LOFAR Software with default parameters. Sorry for this inconvenience.
I guess there will be some more scripts which are not at their appropriate locations, e.g. H5parm_importer.py. You can check every `{{ lofar_directory }}` variable in order if they really exist.

We could think about another parset which is exclusively adapted for the use on CEP3.

In future, this problem will be mitigated when the new `H5parm_exporter` is available. Then these steps will be replaced by the losoto_importer used in `prefactor`.

**Comment by ajstewart** [comment]
@adrabent No problem! Yes I too haven't used it on CEP3 and assumed that how it was set up was the default state, and since I use a virtualenv on top of that I didn't question it.

With the parset at the moment it's safe to change every ```{{ lofar_directory }}/bin``` to ```{{ losoto_directory }}/bin``` as these all refer to losoto tasks. The bin bit is important as ```{{ lofar_directory }}``` is used elsewhere.
