### ISSUE TITLE
libdppp_correctbeam.so

### ISSUE THREAD

**Issue by mknapp55** [lofar-astron/PiLL#25]
NDPPP threw the following error in step time_split-applysol

```
terminate called after throwing an instance of 'casa::AipsError'
  what():  Shared library correctbeam not found in CASACORE_LDPATH or (DY)LD_LIBRARY_PATH
libdppp_correctbeam.so: cannot open shared object file: No such file or directory
```
My NDPPP installation is from Kern and my WSClean is from source since Kern doesn't have WSClean 2.4 yet.  I've run all the way through time_split with the previous version of PiLL and the same NDPPP and have never seen this error.

**Comment by tammojan** [comment]
It simply means that there is no DPPP step called `correctbeam`. It probably means `applybeam`. That can be set with `correctbeam.type = applybeam`

**Comment by mknapp55** [comment]
I'm still getting this error after the update.

**Comment by adrabent** [comment]
Could you please post the time_split-applysol.parset from the subdirectory parsets?

**Comment by mknapp55** [comment]
It's fixed now - I realized I was referencing an older version of PiLL as the `local_directory`.  Question: are parsets overwritten if a step that creates them is rerun?

**Comment by adrabent** [comment]
Yes, parsets are usually overwritten.
