### ISSUE TITLE
Strange new NDPPP error at selfcal-applytec

### ISSUE THREAD

**Issue by mknapp55** [lofar-astron/PiLL#29]
This same error happened for every single .time_split-split MS.  I'm going to rerun from the end of the time_split parset in case there was some issue with the earlier version of PiLL time_split that created these files.
```
Processing 755 time slots ...
DEBUG - Assertion: itsUpper[i-1] <= itsLower[i] || casa::near(itsUpper[i-1],itsLower[i])

2017-07-08 09:48:10 WARNING node.ip-100-64-109-221.executable_args.L563233_SB000_uv_12962EA13t_71MHz_TC0.time_split-split: /usr/bin/NDPPP stderr:
0%LOFAR Exception detected: [AssertError: Assertion: itsUpper[i-1] <= itsLower[i] || casa::near(itsUpper[i-1],itsLower[i])]
in function void LOFAR::BBS::Axis::setup(const std::vector<double>&, const std::vector<double>&, bool)
(/build/lofar-b_IP79/lofar-2.20.2/CEP/ParmDB/src/Axis.cc:117)
```

**Comment by tammojan** [comment]
I've been planning to replace this error text. It means that a solution for a given time exists more than once in the parmdb. Probably removing existing files before starting the run will fix this.

**Comment by mknapp55** [comment]
Yes, removing the existing files did fix it.  Thanks!
