### ISSUE TITLE
Empty 'amp_' plots in plots2

### ISSUE THREAD

**Issue by ajstewart** [lofar-astron/PiLL#7]
Currently all the 'amp_' plots that are generated and saved in plots2 are empty (see example). Is this intentional? As I see there is a min, max argument for these plots:

(526 in the parset) losotoclockamp.argument.LoSoTo.Steps.plotAi1.MinMax          =   [1e-4,3e-3]

These are the only ones that appear empty.

![amp_dirpointing_freq62327575 6836](https://cloud.githubusercontent.com/assets/3306161/22928223/38858eee-f2ad-11e6-8eff-d96c29007422.png)

**Comment by adrabent** [comment]
The limits should be commented out.

**Comment by revoltek** [comment]
New lotoso also will handle no-user-limited plots better
