### ISSUE TITLE
Question: Instrument table numbering when missing sub bands

### ISSUE THREAD

**Issue by ajstewart** [lofar-astron/PiLL#8]
I wonder if there would be a way to incorporate missing sub bands into the final numbering of the instrument tables. For example in one observation I have:

Missing target SBs
- 23
- 25
- 26
- 27
- 29
- 41
- 106
- 113
- 122
- 185
- 199
- 207

Missing calibrator SBs
- 246
- 252
- 313
- 357
- 429

So the calibrator instrument tables are numbered from 000-238 as they are just numbered as they arrive, so when it comes to transferring the tables to targets, you can't just go by the numbers (i.e. instrument-002 -> SB002) because they are out of sync.

Perhaps it needs some sort of 'ideal sub band range' parameter, or number the instrument table by the number of the SB it is taking it from (e.g. calibrator SBXXX-244).

Unless this will be accounted for in a target pipeline?

**Comment by revoltek** [comment]
There is a script "fillmissingSB.py" in my github that create completely flagged SBs when missing, I think that is by far the easiest way, although maybe not optimal, to proceed.

**Comment by adrabent** [comment]
I have a script (used in the long baseline pipeline) which checks the frequency information in instrument tables and matches them directly to measurement sets, e.g, the target. I will adapt this script as mapfile-plugin for the target pipeline.

**Comment by revoltek** [comment]
I think that creating fillers (completely flagged SBs) at the very beginning is saifer and allows you to completely ignore the problem of missing SBs across all the pipelines

**Comment by ajstewart** [comment]
> I think that creating fillers (completely flagged SBs) at the very beginning is saifer and allows you to completely ignore the problem of missing SBs across all the pipelines

I would probably agree on this, saves any extra steps later on and I think would be safer. So it would create dummy instrument tables from the outset? Would these be able to pass through the pipeline without causing an error?

**Comment by adrabent** [comment]
> I think that creating fillers (completely flagged SBs) at the very beginning is saifer and allows you to 
> completely ignore the problem of missing SBs across all the pipelines

I partially agree. Assuming you would have a non-equidistant distribution of subbands in frequency-space, e.g., the frequency difference between SB010, SB011, and SB012 is not the same. This is a typical setup for the HBA surveys.
I think the safest way is to match all calibrated instrument tables with the target frequency bands and once you might concatenate the target measurement sets you fill it up with empty/flagged data. This will safe disk and computation time at least in the calibrator part. And in case you would have an uneven frequency distribution across your subbands you need to do this check anyways.

I think in prefactor this approach has been realized as well.

**Comment by AHorneffer** [comment]
I heard the _p-word_! :-)

Prefactor only adds dummy data when concatenating SBs into one MS per group. For matching the right parmdb (which is created by a script in the pipeline) to the right MS it relies on the fact that the genericpipeline keeps the order of the entries in a mapfile.

But I don't know enough about PILL to understand the actual problem that you have to give a good advice.

**Comment by revoltek** [comment]
The non-equidistance in freq space should not be a problem as long as it is consistent with calibrator and target... however I've never tested it. We are speaking about a few % of disk space considering that usually only a few SB are missing out of hundreds and I am a big fun of "less code is better". Consider also that in the (hopefully near) future NDPPP will output directly h5parm (DD-NDPPP already does) and all these problems will disappear. I would not add extra complication unless this becomes a bottleneck in space/time.

**Comment by adrabent** [comment]
The new version of PiLL should now be able to handle that issue.
Please try out again.
